---
puppetsync:
  permitted_project_types:
    - pupmod
    - pupmod_skeleton
  plans:
    sync:
      # clone_git_repos: false
      stages:
        #        - install_gems
        - checkout_git_feature_branch_in_each_repo
        - ensure_jira_subtask
          ###        - apply_puppet_role
          ###        - remove_el6
        - modernize_gitlab_files
        - lint_gitlab_ci
        - git_commit_changes
        - ensure_github_fork
        - ensure_git_remote
        - git_push_to_remote
        - ensure_gitlab_remote
        - git_push_to_gitlab
        - ensure_github_pr

    approve_github_pr:
      clone_git_repos: false
      stages:
        - install_gems
        - approve_github_pr_for_each_repo

    merge_github_pr:
      clone_git_repos: false
      stages:
        - install_gems
        - merge_github_pr_for_each_repo

jira:
  parent_issue: SIMP-8958
  project: SIMP
  jira_site: https://simp-project.atlassian.net
  subtask_title: 'Standardize assets in %COMPONENT%'
  # optional:
  subtask_story_points: 0
  subtask_assignee: true

git:
  # 0---------1---------2---------3---------4---------5---------6---------7|
  # (SIMP-XXXX) 12345678                                     |
  commit_message: |
    (%JIRA_PARENT_ISSUE%) Standardize assets in %COMPONENT%

    This patch baselines the latest standardized assets for Puppet modules.

    %JIRA_SUBTASK% #close
    [%JIRA_PARENT_ISSUE%] #comment Standardized assets in %COMPONENT%
    [SIMP-8839] #comment Removed EL6 from supported OSes in %COMPONENT%
    [SIMP-8489] #comment Updated %COMPONENT% GLCI pipeline to Puppet 6.18
    [SIMP-8923] #comment Renamed 'sanity' to 'releng' in %COMPONENT%
    [SIMP-8984] #comment Updated %COMPONENT% to new GLCI conventions

github:
  pr_user: op-ct  # This should be the account that *submitted* the PRs (Used
                  # by the idempotency checks when approving/merging PRs)
  proval_message: ':+1: :ghost:'
