---
puppetsync:
  permitted_project_types:
    - pupmod
    - pupmod_skeleton
  plans:
    sync:
      # clone_git_repos: false
      github_api_delay_seconds: 5
      stages:
        #        - install_gems
        - checkout_git_feature_branch_in_each_repo
        - ensure_jira_subtask
        - apply_puppet_role
          #        - remove_el6
        - modernize_gitlab_files
        - lint_gitlab_ci
        - git_commit_changes
        - ensure_github_fork
        - ensure_git_remote
        - git_push_to_remote
        - ensure_gitlab_remote
        - git_push_to_gitlab
        - ensure_github_pr

    approve_github_pr:
      clone_git_repos: false
      stages:
        - install_gems
        - approve_github_pr_for_each_repo

    merge_github_pr:
      clone_git_repos: false
      stages:
        - install_gems
        - merge_github_pr_for_each_repo

jira:
  parent_issue: SIMP-9266
  project: SIMP
  jira_site: https://simp-project.atlassian.net
  subtask_title: 'Improve GHA GLCI trigger logic in %COMPONENT%'
  # optional:
  subtask_story_points: 0
  subtask_assignee: true

git:
  # 0---------1---------2---------3---------4---------5---------6---------7|
  # (SIMP-XXXX) 12345678                                     |
  commit_message: |
    (%JIRA_PARENT_ISSUE%) Improve GHA GCLI trigger in %COMPONENT%

    This patch updates the standardized GitHub Actions that trigger GLCI
    pipelines:

      - Still preemptively cancels existing GLCI pipelines for the same
        branch, EXCEPT when a pipeline is for the same commit hashref.
      - Refactored common GLCI logic into new composite run steps actions:
        - [github-action-gitlab-ci-pipeline-trigger@v1][0]
        - [github-action-gitlab-ci-syntax-check@v1][1]

    This patch also enforces the standardized asset baseline using
    simp/puppetsync, and may apply other updates to ensure conformity.

    CI: SKIP MATRIX
    [%JIRA_SUBTASK%] #close
    [%JIRA_PARENT_ISSUE%] #comment Standardized GHA + assets in %COMPONENT%
    [SIMP-9279] #comment `.fixtures.yml` triggers GLCI acc for %COMPONENT%

    [0]: https://github.com/simp/github-action-gitlab-ci-pipeline-trigger
    [1]: https://github.com/simp/github-action-gitlab-ci-syntax-check

github:
  pr_user: op-ct  # This should be the account that *submitted* the PRs (Used
                  # by the idempotency checks when approving/merging PRs)
  proval_message: ':+1: :ghost:'
