---
puppetsync:
  permitted_project_types:
    - pupmod
    - pupmod_skeleton
  plans:
    sync:
      # clone_git_repos: false
      stages:
        #        - install_gems
        - checkout_git_feature_branch_in_each_repo
###        - ensure_jira_subtask
        - apply_puppet_role
        - remove_el6
        - modernize_gitlab_files
        - lint_gitlab_ci
###        - git_commit_changes
###        - ensure_github_fork
###        - ensure_git_remote
###        - git_push_to_remote
###        - ensure_gitlab_remote
###        - git_push_to_gitlab
###        - ensure_github_pr

    approve_github_pr:
      clone_git_repos: false
      stages:
        - install_gems
        - approve_github_pr_for_each_repo

    merge_github_pr:
      clone_git_repos: false
      stages:
        - install_gems
        - merge_github_pr_for_each_repo

jira:
  parent_issue: SIMP-9126
  project: SIMP
  jira_site: https://simp-project.atlassian.net
  subtask_title: 'Add GHA CI/CD workflows to %COMPONENT%'
  # optional:
  subtask_story_points: 0
  subtask_assignee: true

git:
  # 0---------1---------2---------3---------4---------5---------6---------7|
  # (SIMP-XXXX) 12345678                                     |
  commit_message: |
    (%JIRA_PARENT_ISSUE%) Add GHA workflows to %COMPONENT%

    The primary purpose of this update is to add standardized GitHub Actions
    to provide GitHub-based CI/CD workflows.  Among this first batch are

    * PR: Puppet module tests & test matrix
    * PR: Auto-trigger corresponding GLCI pipeline if actor has write access
    * PR close: Clean up any auto-triggered GLCI pipelines/branches

    This patch enforces the standardized asset baseline, and may apply other
    updates to ensure conformity.

    %JIRA_SUBTASK% #close
    [%JIRA_PARENT_ISSUE%] #comment Standardized GHA + assets in %COMPONENT%

github:
  pr_user: op-ct  # This should be the account that *submitted* the PRs (Used
                  # by the idempotency checks when approving/merging PRs)
  proval_message: ':+1: :ghost:'
